---
AWSTemplateFormatVersion: "2010-09-09"

Description: >
  This template will automatically deploy a reference architecture for the Pivotal Cloud Foundry stack.
  For a detailed guide on how to deploy this template, please read the instructions QS(qs-1ngltrcpf)

Parameters:
  NATInstanceType:
    Type: String
    AllowedValues:
    - t2.micro
    - t2.small
    - t2.medium
    - t2.large
    - t2.xlarge
    - m4.large
    - c4.large
    - m4.xlarge
    - c4.xlarge
    - c4.8xlarge
    ConstraintDescription: Instance Type must be of a valid EC2 type
    Default: t2.medium
    Description: Select the Instance Type to use for the NAT vm
  OpsManagerIngress:
    Type: String
    Default: 0.0.0.0/0
    Description: CIDR range allowed to connect to Ops Manager instance
  RdsDBName:
    Type: String
    MinLength: '4'
    Default: bosh
    Description: BOSH database name
  RdsUsername:
    Type: String
    Description: BOSH database username
  RdsPassword:
    Type: String
    NoEcho: 'true'
    MinLength: '8'
    AllowedPattern: "[\\w-_]*"
    Description: BOSH database password
  SSLCertificateARN:
    Type: String
    Description: ARN for pre-uploaded SSL certificate
  OpsManagerTemplate:
    Type: String
    Default: https://s3.amazonaws.com/quickstart-reference/pivotal/cloudfoundry/latest/templates/ops-manager.json
    Description: S3 Location for OpsManager CloudFormation Template
  CloudFoundryTemplate:
    Type: String
    Default: https://s3.amazonaws.com/quickstart-reference/pivotal/cloudfoundry/latest/templates/cloud-formation.json
    Description: S3 Location for Base Deployment CloudFormation Template
  PCFAutomationRelease:
    Type: String
    Default: https://s3.amazonaws.com/quickstart-reference/pivotal/cloudfoundry/latest/scripts/quickstart.tgz
    Description: S3 Location for Base Deployment CloudFormation Template
  ElbPrefix:
    Type: String
    Description: 'Prefix for the name of the ELBs generated. Required.'
    MinLength: 1
    MaxLength: 19
  AllowHttpOnElb:
    Type: String
    Default: 'true'
    AllowedValues:
    - 'true'
    - 'false'
    Description: 'Allow HTTP traffic on PCF-ELB port 80. Default: true.'
  PivnetToken:
    Type: String
    Description: Using the Pivnet CLI requires a valid Pivotal Network API token. See
      https://network.pivotal.io/docs/api#how-to-authenticate
  AdminEmail:
    Type: String
    Description: Admin email used by mysql monitor, for example
  HostedZoneId:
    Type: AWS::Route53::HostedZone::Id
    Description: Existing hosted zone to create DNS records under
  Domain:
    Type: String
    Description: Root or subdomain for all Pivotal Cloud Foundry DNS entries (e.g. - example.com or pcf.example.com). Must match hosted zone.
  OpsManagerAdminPassword:
    Type: String
    NoEcho: 'true'
    MinLength: '14'
    AllowedPattern: "[\\w-_]*"
    Description: Admin password to log on to OpsManager. At least 14 characters from the set of alphanumeric, dashes, and underscores.
  PCFKeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Select the SSH keypair to use for Ops Manager and all VMS in the deployment
  NumberOfAZs:
    Type: Number
    AllowedValues: [1,2]
    Default: 1
    Description: Select number of Avalaibility Zones (either 1 or 2)
  ForwardLogOutput:
    Description: |
      When true, bootstrap logs are sent to 'CloudWatch Logs'. Critical for solving failures, but
      potentially exposes secrets output to logs as part of the bootstrap process.
    Type: String
    Default: 'true'
    AllowedValues:
    - 'true'
    - 'false'
  SkipSSLValidation:
    Description: |
      When true, SSL certificates are not validated. Not appropriate for a production environment.
    Type: String
    AllowedValues:
    - 'true'
    - 'false'
Rules:
  KeyPairsNotEmpty:
    Assertions:
    - Assert:
        Fn::Not:
        - Fn::EachMemberEquals:
          - Fn::RefAll: AWS::EC2::KeyPair::KeyName
          - ""
      AssertDescription: All key pair parameters must not be empty
  SupportedRegionRule:
      Assertions:
      - Assert:
          Fn::Contains:
          - {{supported_regions}}
          - !Ref AWS::Region
        AssertDescription: This Quick Start is only available in a subset of regions. {{supported_regions}}
Mappings:
  AMIMapping:
    {{ami_mapping | indent}}
Resources:
  ## cloud-formation.json
  PCFBase:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        01NATKeyPair: !Ref PCFKeyPair
        02NATInstanceType: !Ref NATInstanceType
        03OpsManagerIngress: !Ref OpsManagerIngress
        04RdsDBName: !Ref RdsDBName
        05RdsUsername: !Ref RdsUsername
        06RdsPassword: !Ref RdsPassword
        07SSLCertificateARN: !Ref SSLCertificateARN
        08OpsManagerTemplate: !Ref OpsManagerTemplate
        09ElbPrefix: !Ref ElbPrefix
        10AllowHttpOnElb: !Ref AllowHttpOnElb
        11PivnetToken: !Ref PivnetToken
        12AdminEmail: !Ref AdminEmail
      TemplateURL: !Ref CloudFoundryTemplate
  ## Custom resource stuff
  CustomResourceSQSQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: CustomResourceSQSQueue
      VisibilityTimeout: 1
  CustomResourceSNSTopic:
    Type: "AWS::SNS::Topic"
    Properties:
      DisplayName: custom-resource-topic
      Subscription:
        - Endpoint: !GetAtt CustomResourceSQSQueue.Arn
          Protocol: sqs
  CustomResourceSQSQueuePolicy:
    Type: "AWS::SQS::QueuePolicy"
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS: "*"
            Action: "sqs:SendMessage"
            Resource: !GetAtt CustomResourceSQSQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref CustomResourceSNSTopic
      Queues:
        - !Ref CustomResourceSQSQueue
  MyCustomBOSH:
    Type: Custom::BOSH
    Version: 1.0
    Properties:
      ServiceToken: !Ref CustomResourceSNSTopic
    DependsOn:
    - CustomResourceSQSQueuePolicy
    - BootstrapInstance
    - OpsManagerInstance
    - DNSOpsMan
    - DNSSys
    - DNSStar
    - DNS
    - DNSApps
    - PCFDescribeStackPolicy
    - PCFParameterStorePolicy
    - PCFCustomResourcePolicy
    - PCFEmitLogsPolicy
    - SSMParameterJSON
  WaitHandle:
    Type: "AWS::CloudFormation::WaitConditionHandle"
  WaitCondition:
    Type: "AWS::CloudFormation::WaitCondition"
    Properties:
      Handle:
        Ref: "WaitHandle"
      Timeout: "14400"
      Count: 1
  ## This Policy is for Allowing the OpsManager EC2 Instance access to the Describe stack and
  ## Stored Parameters.
  PCFDescribeStackPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action:
              - "cloudformation:DescribeStacks"
            Resource: !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/${AWS::StackName}/*"
      PolicyName: !Sub ${AWS::StackName}-describe-stack
      Roles:
        - !GetAtt PCFBase.Outputs.PcfIamRole
  PCFParameterStorePolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action:
              - "ssm:DescribeParameters"
              - "ssm:GetParameters"
            Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${AWS::StackName}.*"
      PolicyName: !Sub ${AWS::StackName}-parameter-store
      Roles:
        - !GetAtt PCFBase.Outputs.PcfIamRole
  PCFCustomResourcePolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action: "sqs:*"
            Resource: !GetAtt CustomResourceSQSQueue.Arn
      PolicyName: !Sub ${AWS::StackName}-custom-resource
      Roles:
        - !GetAtt PCFBase.Outputs.PcfIamRole
  PCFEmitLogsPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              - logs:DescribeLogStreams
            Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:pcf-bootstrap-${AWS::StackName}:*"
      PolicyName: !Sub ${AWS::StackName}-emit-logs-policy
      Roles:
        - !GetAtt PCFBase.Outputs.PcfIamRole
  ## This is the Start of our Secured Parameters
  SSMParameterJSON:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "${AWS::StackName}.SSMParameterJSON"
      Description: JSON Array of All SSM Passed Parameters
      Type: String
      Value: !Sub |
        {
        "PcfRdsPassword": "${PCFBase.Outputs.PcfRdsPassword}",
        "PcfPublicSubnetId2": "${PCFBase.Outputs.PcfPublicSubnetId2}",
        "PcfElasticRuntimeS3PackagesBucket": "${PCFBase.Outputs.PcfElasticRuntimeS3PackagesBucket}",
        "PcfNumberOfAZs": "${NumberOfAZs}",
        "PcfPublicSubnetAvailabilityZone": "${PCFBase.Outputs.PcfPublicSubnetAvailabilityZone}",
        "PcfIamRole": "${PCFBase.Outputs.PcfIamRole}",
        "PcfElasticRuntimeS3ResourcesBucket": "${PCFBase.Outputs.PcfElasticRuntimeS3ResourcesBucket}",
        "PcfRdsPort": "${PCFBase.Outputs.PcfRdsPort}",
        "PcfOpsManagerS3Bucket": "${PCFBase.Outputs.PcfOpsManagerS3Bucket}",
        "PcfIamUserName": "${PCFBase.Outputs.PcfIamUserName}",
        "PcfPublicSubnetAvailabilityZone2": "${PCFBase.Outputs.PcfPublicSubnetAvailabilityZone2}",
        "PcfPrivateSubnetId": "${PCFBase.Outputs.PcfPrivateSubnetId}",
        "PcfIamUserAccessKey": "${PCFBase.Outputs.PcfIamUserAccessKey}",
        "PcfPublicSubnetId": "${PCFBase.Outputs.PcfPublicSubnetId}",
        "PcfRdsDBName": "${PCFBase.Outputs.PcfRdsDBName}",
        "PcfVmsSecurityGroupId": "${PCFBase.Outputs.PcfVmsSecurityGroupId}",
        "PcfElbTcpDnsName": "${PCFBase.Outputs.PcfElbTcpDnsName}",
        "PcfPrivateSubnet2AvailabilityZone": "${PCFBase.Outputs.PcfPrivateSubnet2AvailabilityZone}",
        "PcfWaitHandle": "${WaitHandle}",
        "PcfOpsManagerAdminPassword": "${OpsManagerAdminPassword}",
        "PcfRdsAddress": "${PCFBase.Outputs.PcfRdsAddress}",
        "PcfElbDnsName": "${PCFBase.Outputs.PcfElbDnsName}",
        "PcfOpsManagerInstanceIP": "${OpsManagerInstance.PublicIp}",
        "PcfPrivateSubnetAvailabilityZone": "${PCFBase.Outputs.PcfPrivateSubnetAvailabilityZone}",
        "PcfCustomResourceSQSQueueUrl": "${CustomResourceSQSQueue}",
        "PcfVpc": "${PCFBase.Outputs.PcfVpc}",
        "PcfElasticRuntimeS3DropletsBucket": "${PCFBase.Outputs.PcfElasticRuntimeS3DropletsBucket}",
        "PcfPrivateSubnet2Id": "${PCFBase.Outputs.PcfPrivateSubnet2Id}",
        "PcfIamUserSecretAccessKey": "${PCFBase.Outputs.PcfIamUserSecretAccessKey}",
        "PcfElbSshDnsName": "${PCFBase.Outputs.PcfElbSshDnsName}",
        "PcfElasticRuntimeS3BuildpacksBucket": "${PCFBase.Outputs.PcfElasticRuntimeS3BuildpacksBucket}",
        "PcfOpsManagerSecurityGroupId": "${PCFBase.Outputs.PcfOpsManagerSecurityGroupId}",
        "PcfRdsUsername": "${PCFBase.Outputs.PcfRdsUsername}"
        }
  ## This is the End of our Secured Parameters
  ## This is the EC2 Ops Manager
  OpsManagerInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [AMIMapping, !Ref "AWS::Region", "opsman"]
      InstanceType: m4.large
      IamInstanceProfile: !GetAtt PCFBase.Outputs.PcfIamInstanceProfile
      KeyName: !Ref PCFKeyPair
      Monitoring: true
      BlockDeviceMappings:
        - DeviceName: "/dev/xvda"
          Ebs:
            DeleteOnTermination: true
            VolumeSize: 100
            VolumeType: gp2
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet:
            - !GetAtt PCFBase.Outputs.PcfOpsManagerSecurityGroupId
          SubnetId: !GetAtt PCFBase.Outputs.PcfPublicSubnetId
      SourceDestCheck: true
      Tags:
        - Key: Name
          Value: "PCF Ops Manager"
  BootstrapInstance:
    Type: AWS::EC2::Instance
    CreationPolicy:
      ResourceSignal:
        Timeout: PT30M
    DependsOn: OpsManagerInstance
    Properties:
      ImageId: !FindInMap [AMIMapping, !Ref "AWS::Region", "bootstrap"]
      InstanceType: t2.micro
      IamInstanceProfile: !GetAtt PCFBase.Outputs.PcfIamInstanceProfile
      KeyName: !Ref PCFKeyPair
      Monitoring: true
      BlockDeviceMappings:
        - DeviceName: "/dev/sda1"
          Ebs:
            DeleteOnTermination: true
            VolumeSize: 50
            VolumeType: gp2
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet:
            - !GetAtt PCFBase.Outputs.PcfOpsManagerSecurityGroupId
          SubnetId: !GetAtt PCFBase.Outputs.PcfPublicSubnetId
      SourceDestCheck: true
      Tags:
        - Key: Name
          Value: "PCF Bootstrap"
      UserData: !Base64
        "Fn::Sub": |
          #!/bin/bash

          cfn-init -v --stack ${AWS::StackName} --resource BootstrapInstance --region ${AWS::Region}
          cfn-signal -e $? --stack ${AWS::StackName} --resource BootstrapInstance --region ${AWS::Region}

          su ubuntu -c /home/ubuntu/quickstart/bootstrap.sh
    Metadata:
      AWS::CloudFormation::Init:
        config:
          sources:
            '/home/ubuntu': !Ref PCFAutomationRelease
          files:
            /home/ubuntu/scripts/awslogs.config:
              owner: ubuntu
              group: ubuntu
              content: !Sub |
                [general]
                state_file = /var/awslogs/state/agent-state

                [/var/log/syslog]
                file = /var/log/syslog
                log_group_name = pcf-bootstrap-${AWS::StackName}
                log_stream_name = syslog
                datetime_format = %b %d %H:%M:%S

                [/var/log/cloud-init-output.log]
                file = /var/log/cloud-init-output.log
                log_group_name = pcf-bootstrap-${AWS::StackName}
                log_stream_name = cloud-init-output.log

                [/var/log/cloud-init.log]
                file = /var/log/cloud-init.log
                log_group_name = pcf-bootstrap-${AWS::StackName}
                log_stream_name = cloud-init.log

                [/var/log/cfn-init-cmd.log]
                file = /var/log/cfn-init-cmd.log
                log_group_name = pcf-bootstrap-${AWS::StackName}
                log_stream_name = cfn-init-cmd.log

                [/var/log/cfn-init.log]
                file = /var/log/cfn-init.log
                log_group_name = pcf-bootstrap-${AWS::StackName}
                log_stream_name = cfn-init.log

                [/var/log/cfn-wire.log]
                file = /var/log/cfn-wire.log
                log_group_name = pcf-bootstrap-${AWS::StackName}
                log_stream_name = cfn-wire.log
            /var/local/cloudformation/stack-meta.json:
              content: !Sub |
                {"StackName":"${AWS::StackName}","StackId":"${AWS::StackId}","Region":"${AWS::Region}"}
              mode: '000755'
          commands:
            a_log_setup:
              command: !Sub |
                if "${ForwardLogOutput}" == "true"; then
                   echo "Setting up CloudWatch Logs."
                   python3 /home/ubuntu/scripts/awslogs-agent-setup.py -n -r ${AWS::Region} -c /home/ubuntu/scripts/awslogs.config
                else
                  echo "Skipping CloudWatch Logs, ForwardLogOutput was false"
                fi
            b_chmod_stuff:
              command: |
                chown -R ubuntu:ubuntu /home/ubuntu/quickstart
            c_copy_version_confifg_to_known_location:
              command: |
                cp /home/ubuntu/quickstart/version_config.json /var/local/version_config.json
            d_install_delete_daemon:
              command: |
                /home/ubuntu/quickstart/daemon/install.sh

  DNSOpsMan:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub opsman.${Domain}
      ResourceRecords:
        - !Sub "${OpsManagerInstance.PublicIp}"
      TTL: 60
      Type: A
  DNS:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub bootstrap.${Domain}
      ResourceRecords:
        - !Sub "${BootstrapInstance.PublicIp}"
      TTL: 60
      Type: A
  DNSStar:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub "*.${Domain}"
      ResourceRecords:
        - !GetAtt PCFBase.Outputs.PcfElbDnsName
      TTL: 60
      Type: CNAME
  DNSSsh:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub ssh.sys.${Domain}
      ResourceRecords:
        - !GetAtt PCFBase.Outputs.PcfElbSshDnsName
      TTL: 60
      Type: CNAME
  DNSSys:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub "*.sys.${Domain}"
      ResourceRecords:
        - !GetAtt PCFBase.Outputs.PcfElbDnsName
      TTL: 60
      Type: CNAME
  DNSApps:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub "*.apps.${Domain}"
      ResourceRecords:
        - !GetAtt PCFBase.Outputs.PcfElbDnsName
      TTL: 60
      Type: CNAME
Outputs:
  OpsManager:
    Description: Url For Logging into OpsManager
    Value: !Sub "https://opsman.${Domain}"
