---

resources:
- name: quickstart-github-release
  type: github-release
  source:
    owner: cf-platform-eng
    repository: quickstart
    access_token: {{github_access_token}}

- name: pivnet-release
  type: github-release
  source:
    owner: pivotal-cf
    repository: pivnet-cli
    access_token: {{github_access_token}}
    version: v0.0.49

- name: om-release
  type: github-release
  source:
    owner: pivotal-cf
    repository: om
    access_token: {{github_access_token}}
    version: v0.0.22

- name: quickstart-repo
  type: git
  source:
    branch: master
    uri: https://github.com/cf-platform-eng/quickstart
    username: cholick
    password: {{github_access_token}}
    ignore_paths:
      - ci/*.yml

- name: version
  type: semver
  source:
    driver: git
    uri: https://github.com/cf-platform-eng/quickstart
    branch: quickstart_release_version
    file: quickstart_release_version
    username: cholick
    password: {{github_access_token}}

- name: quickstart-versioned-release
  type: s3
  source:
    bucket: aws-pcf-quickstart-releases
    region_name: us-west-2
    regexp: quickstart-(.*).tgz
    access_key_id: {{s3_access_key_id}}
    secret_access_key: {{s3_secret_access_key}}

- name: quickstart-latest-release-candidate
  type: s3
  source:
    bucket: aws-pcf-quickstart-releases
    region_name: us-west-2
    versioned_file: quickstart-release-candidate.tgz
    access_key_id: {{s3_access_key_id}}
    secret_access_key: {{s3_secret_access_key}}

# latest is manual
- name: quickstart-latest-release
  type: s3
  source:
    bucket: aws-pcf-quickstart-releases
    region_name: us-west-2
    versioned_file: quickstart-release.tgz
    access_key_id: {{s3_access_key_id}}
    secret_access_key: {{s3_secret_access_key}}


jobs:
- name: github-release
  plan:
  - get: pivnet-release
  - get: om-release
  - get: quickstart-repo
  - get: version
    params:
      bump: patch
  - task: build-release
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: python
          tag: "3"
      inputs:
      - name: pivnet-release
      - name: om-release
      - name: quickstart-repo
      - name: version
      outputs:
      - name: output
      run:
        path: bash
        args:
        - -exc
        - |
          mkdir -p quickstart
          mkdir -p quickstart/bin
          cp -r quickstart-repo/* quickstart
          cp om-release/om-linux quickstart/bin/om
          chmod +x quickstart/bin/om
          cp pivnet-release/pivnet-linux* quickstart/bin/pivnet
          chmod +x quickstart/bin/pivnet
          pushd quickstart
          mkdir -p vendor
          pip download --no-binary :all: --dest vendor -r requirements.txt
          popd

          mkdir -p output
          tar -czvf output/quickstart-`cat version/version`.tgz quickstart
  - put: version
    params:
      file: version/version
  - put: quickstart-github-release
    params:
      name: version/version
      tag: version/version
      globs:
      - output/quickstart-*.tgz

- name: build-quickstart-release-candidate
  plan:
  - get: version
    passed:
      - github-release
  - get: quickstart-github-release
    trigger: true
    passed:
      - github-release
  - put: quickstart-versioned-release
    params:
      file: quickstart-github-release/quickstart-*.tgz
  - put: quickstart-latest-release-candidate
    params:
      file: quickstart-github-release/quickstart-*.tgz

- name: build-quickstart-release
  plan:
  - get: version
    passed:
      - build-quickstart-release-candidate
  - get: quickstart-latest-release-candidate
    passed:
      - build-quickstart-release-candidate
  - put: quickstart-latest-release
    params:
      file: quickstart-latest-release-candidate/quickstart-*.tgz
