---

resources:
- name: quickstart-repo
  type: git
  source:
    branch: master
    uri: https://github.com/cf-platform-eng/quickstart
    username: cholick
    password: {{github_access_token}}
    ignore_paths:
      - ci/*.yml

- name: om-release
  type: github-release
  source:
    owner: pivotal-cf
    repository: om
    access_token: {{github_access_token}}
    version: v0.0.22

jobs:
- name: integration-test
  plan:
  - get: quickstart-repo
    trigger: false
  - task: integration-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: python
          tag: "3"
      inputs:
      - name: quickstart-repo
      params:
        AWS_CF_PASSWORD: {{aws_cf_password}}
        AWS_CF_DOMAIN: {{aws_cf_domain}}
        AWS_CF_HOSTEDZONEID: {{aws_cf_hostedzoneid}}
        AWS_CF_SSLCERTIFICATEARN: {{aws_cf_sslcertificatearn}}
        AWS_CF_NATKEYPAIR: {{aws_cf_natkeypair}}
        AWS_CF_PIVNETTOKEN: {{aws_cf_pivnettoken}}
        AWS_ACCESS_KEY_ID: {{aws_admin_key_id}}
        AWS_SECRET_ACCESS_KEY: {{aws_admin_secret_access_key}}
        AWS_INTEGRATION_REGION: {{aws_integration_region}}
      run:
        path: bash
        args:
        - -exc
        - |
          pushd quickstart-repo
          pip install -r requirements.txt
          python ./ci/create-stack.py
          popd

- name: check-status
  plan:
  - get: om-release
  - get: quickstart-repo
    passed: [ integration-test ]
    trigger: true
  - task: check-status
    attempts: 10
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: cfplatformeng/quickstart-ci
      inputs:
      - name: om-release
      - name: quickstart-repo
      params:
        AWS_CF_PASSWORD: {{aws_cf_password}}
        AWS_CF_DOMAIN: {{aws_cf_domain}}
      run:
        path: bash
        args:
        - -exc
        - |
          mv om-release/om-linux /usr/local/bin/om
          chmod +x /usr/local/bin/om
          pushd quickstart-repo
          pip install -r requirements.txt
          sleep 30
          python ./ci/check-status.py
          popd
